# Confirm that the config file si valid:
# https://circleci.com/docs/2.0/local-cli/

version: 2

aliases:
  - &workspace-root ~/marketing-components

  - &container
    working_directory: *workspace-root
    docker:
      - image: circleci/node:lts

  - &attach-workspace
    attach-workspace:
      at: *workspace-root

  - &persist-workspace
    persist_to_workspace:
      root: .
      paths:
        - '*'

  - &install
    name: Install dependencies
    command: yarn install --frozen-lockfile

  - &build
    name: Build packages
    command: yarn build

  - &deploy-docs
    name: Deploy docs
    command: yarn docs:deploy

  - &lerna-publish
    name: Publish packages
    command: npx lerna publish -m "[skip ci] Release" --yes

  - &conventional-commit-lint
    name: Conventional Commits check
    command: npx commitlint -f $(git log --author=CircleCI -1 --format=format:"%H") -V

  - &test
    name: Test packages
    command: yarn test

  - &add-npm-release-token
    name: Set NPM publish token
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc

  - &set-github-credentials
    name: Set github credentials
    command: |
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git config --global user.email "circleci@transferwise.com"
      git config --global user.name "CircleCI"

  - &save-yarn-cache
    key: yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

  - &restore-yarn-cache
    keys:
      - yarn-cache-{{ checksum "yarn.lock" }}
      - yarn-cache-

jobs:
  install:
    <<: *container
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: *install
      - *persist-workspace
      - save_cache: *save-yarn-cache

  build:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build
      - *persist-workspace

  test:
    <<: *container
    steps:
      - *attach-workspace
      - run: *test
      - *persist-workspace

  test-main:
    <<: *container
    steps:
      - *attach-workspace
      - run: *test
      - *persist-workspace

  deploy-docs:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build
      - run: *set-github-credentials
      - run: *deploy-docs

  deploy-docs-for-branch:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build
      - run: *set-github-credentials
      - run: *deploy-docs

  conventional-commit-lint:
    <<: *container
    steps:
      - *attach-workspace
      - run: *conventional-commit-lint

  publish:
    <<: *container
    steps:
      - *attach-workspace
      - run: *set-github-credentials
      - run: *add-npm-release-token
      - run: *lerna-publish

workflows:
  version: 2
  build-deploy-release:
    jobs:
      - install:
          context: frontend-build
          filters:
            branches:
              ignore: gh-pages

      - conventional-commit-lint:
          context: frontend-build
          requires:
            - install
          filters:
            branches:
              ignore: gh-pages

      # Build has to run before test as yarn workspace symlink the dependencies.
      - build:
          context: frontend-build
          filters:
            branches:
              ignore: gh-pages
          requires:
            - install

      # On current branch the flow should NOT be blocked if there is an error in commit message
      - test:
          context: frontend-build
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - main

      # On main the flow should be blocked if there is an error in commit message
      - test-main:
          context: frontend-build
          requires:
            - build
            - conventional-commit-lint
          filters:
            branches:
              only: main

      - deploy-docs-for-branch:
          context: frontend-build
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - main

      - deploy-docs:
          context: frontend-build
          requires:
            - test-main
          filters:
            branches:
              only: main

      - publish:
          context: frontend-publish
          requires:
            - test-main
          filters:
            branches:
              only: main
