export { default as ASICRegulated } from './ASICRegulated';
export { default as CanstarAward } from './CanstarAward';
export { default as Customers } from './Customers';
export { default as FCARegulated } from './FCARegulated';
export { default as Mitsui } from './Mitsui';
export { default as StraitsTimes } from './StraitsTimes';
export { default as Trustpilot } from './Trustpilot';
export { default as TUVApproved } from './TUVApproved';
export { default as FSRAApproved } from './FSRAApproved';
